services:
  mbs:
    image: node:22
    working_dir: /mbs
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${APP_PORT}:3000
      - ${PRISMA_STUDIO_PORT}:5555
    volumes:
      - ./mbs:/mbs
    command: sh -c "npm install && npx prisma migrate deploy && npx prisma generate && npm run dev"

  db:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db:/var/lib/postgresql/data
