name: Notify Teams on Issue Status Change to In Review

on:
  issues:
    types: [edited]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check issue status
        id: check_status
        run: |
          if [[ "${{ github.event.changes.project_card.status.from }}" != "In review" && "${{ github.event.issue.project_card.status }}" == "In review" ]]; then
            echo "status_changed=true" >> $GITHUB_ENV
          else
            echo "status_changed=false" >> $GITHUB_ENV
          fi

      - name: Fetch issue details
        if: env.status_changed == 'true'
        id: fetch_issue
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }})
          echo "Response: $response"
          logins=$(echo $response | jq -r '[.assignees[] | .login | tostring]' | jq -c '.')
          echo "::set-output name=assignees::$logins"

      - name: Send notification to Teams
        if: env.status_changed == 'true'
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.NOTIFY_PENDING_REVIEW_WEBHOOK_KEY }}
        run: |
          assignees=$(echo ${{ steps.fetch_issue.outputs.assignees }} | jq -c '. | join(", ")')
          PAYLOAD=$(cat <<EOF
          {
            "text": "Pending Review",
            "issue_number": "${{ github.event.issue.number }}",
            "issue_title": "${{ github.event.issue.title }}",
            "issue_url": "${{ github.event.issue.html_url }}",
            "assignees": "$assignees"
          }
          EOF
          )
          curl -H "Content-Type: application/json" -d "$PAYLOAD" $TEAMS_WEBHOOK_URL
